#!/usr/bin/env bash
# deploy/build.sh — Pulse deployment build step
# ─────────────────────────────────────────────
# Generates pulse-config.local.js from environment variables.
# Run by Cloudflare Pages as the build command: bash deploy/build.sh
#
# Required env vars (set per-environment in Cloudflare Pages dashboard):
#   PULSE_SUPABASE_URL        — Supabase project URL
#   PULSE_SUPABASE_ANON_KEY   — Supabase anon/public key (safe for browser)
#   PULSE_STORAGE_BACKEND     — 'supabase' for all deployed envs
#   PULSE_ENV                 — 'staging' | 'production'
#
# Optional:
#   PULSE_BUILD_VERSION       — override version tag (defaults to git short SHA)

set -euo pipefail

# ── Validate required env vars ──────────────────────────────
: "${PULSE_SUPABASE_URL:?ERROR: PULSE_SUPABASE_URL is not set}"
: "${PULSE_SUPABASE_ANON_KEY:?ERROR: PULSE_SUPABASE_ANON_KEY is not set}"
: "${PULSE_STORAGE_BACKEND:=supabase}"
: "${PULSE_ENV:=production}"

# Derive build version from git SHA if not explicitly provided
PULSE_BUILD_VERSION="${PULSE_BUILD_VERSION:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}"

echo "[build] Pulse deployment build"
echo "[build] Environment : $PULSE_ENV"
echo "[build] Storage     : $PULSE_STORAGE_BACKEND"
echo "[build] Build ver   : $PULSE_BUILD_VERSION"
echo "[build] Supabase URL: $PULSE_SUPABASE_URL"

# ── Generate pulse-config.local.js ──────────────────────────
cat > pulse-config.local.js <<EOF
// pulse-config.local.js — AUTO-GENERATED by deploy/build.sh
// DO NOT EDIT — regenerated on every deploy
// Environment: ${PULSE_ENV}
// Build: ${PULSE_BUILD_VERSION}

window.PULSE_SUPABASE_URL = '${PULSE_SUPABASE_URL}';
window.PULSE_SUPABASE_ANON_KEY = '${PULSE_SUPABASE_ANON_KEY}';
window.PULSE_STORAGE_BACKEND = '${PULSE_STORAGE_BACKEND}';
window.PULSE_ENV = '${PULSE_ENV}';
window.PULSE_BUILD_VERSION = '${PULSE_BUILD_VERSION}';
EOF

echo "[build] Generated pulse-config.local.js"

# ── Inject build version into HTML cache-buster query strings ──
# Replaces ?v=<anything> on shared.js, supabase-client.js, auth.js
# so browsers pick up new code on every deploy without manual edits.
if command -v sed &>/dev/null; then
  echo "[build] Updating cache-buster version in HTML files..."
  for f in *.html; do
    sed -i.bak \
      -e "s|shared\.js?v=[^\"']*|shared.js?v=${PULSE_BUILD_VERSION}|g" \
      -e "s|supabase-client\.js?v=[^\"']*|supabase-client.js?v=${PULSE_BUILD_VERSION}|g" \
      -e "s|auth\.js?v=[^\"']*|auth.js?v=${PULSE_BUILD_VERSION}|g" \
      "$f"
    rm -f "${f}.bak"
  done
  echo "[build] Cache-buster updated to $PULSE_BUILD_VERSION in all HTML files"
fi

echo "[build] Done — publish directory: ."
