#!/usr/bin/env bash
# deploy/build.sh — Pulse deployment build step
# ─────────────────────────────────────────────
# Generates js/pulse-config.local.js from environment variables.
# Run on deploy (Vercel vercel.json, Cloudflare Pages, or GitHub Actions):
#   bash deploy/build.sh
#
# Required env vars (set per-environment in Cloudflare Pages dashboard):
#   PULSE_SUPABASE_URL        — Supabase project URL
#   PULSE_SUPABASE_ANON_KEY   — Supabase anon/public key (safe for browser)
#   PULSE_STORAGE_BACKEND     — 'supabase' for all deployed envs
#   PULSE_ENV                 — 'staging' | 'production'
#
# Optional:
#   PULSE_BUILD_VERSION       — override version tag (defaults to git short SHA)

set -euo pipefail

# Accept PULSE_* (deploy scripts) or VITE_* (common Vercel naming)
PULSE_SUPABASE_URL="${PULSE_SUPABASE_URL:-${VITE_SUPABASE_URL:-}}"
PULSE_SUPABASE_ANON_KEY="${PULSE_SUPABASE_ANON_KEY:-${VITE_SUPABASE_ANON_KEY:-}}"

# ── Reject service-role / secret keys (browser must use anon key only) ──
if [[ "$PULSE_SUPABASE_ANON_KEY" == sb_secret_* ]]; then
  echo "[build] ERROR: VITE_SUPABASE_ANON_KEY / PULSE_SUPABASE_ANON_KEY is a SECRET key (sb_secret_...)."
  echo "[build] Use the anon PUBLIC key from Supabase → Settings → API → anon public (starts with eyJ...)."
  echo "[build] Rotate the exposed secret key in Supabase immediately if it was deployed to the browser."
  exit 1
fi
if echo "$PULSE_SUPABASE_ANON_KEY" | grep -q 'service_role'; then
  echo "[build] ERROR: JWT contains service_role — use the anon public key only."
  exit 1
fi

# ── Validate required env vars ──────────────────────────────
: "${PULSE_SUPABASE_URL:?ERROR: Set PULSE_SUPABASE_URL or VITE_SUPABASE_URL in Vercel}"
: "${PULSE_SUPABASE_ANON_KEY:?ERROR: Set PULSE_SUPABASE_ANON_KEY or VITE_SUPABASE_ANON_KEY in Vercel}"
: "${PULSE_STORAGE_BACKEND:=supabase}"
: "${PULSE_ENV:=production}"

# Derive build version from git SHA if not explicitly provided
PULSE_BUILD_VERSION="${PULSE_BUILD_VERSION:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}"

echo "[build] Pulse deployment build"
echo "[build] Environment : $PULSE_ENV"
echo "[build] Storage     : $PULSE_STORAGE_BACKEND"
echo "[build] Build ver   : $PULSE_BUILD_VERSION"
echo "[build] Supabase URL: $PULSE_SUPABASE_URL"

mkdir -p js pages

# ── Generate js/pulse-config.local.js ──────────────────────────
cat > js/pulse-config.local.js <<EOF
// pulse-config.local.js — AUTO-GENERATED by deploy/build.sh
// DO NOT EDIT — regenerated on every deploy
// Environment: ${PULSE_ENV}
// Build: ${PULSE_BUILD_VERSION}

window.PULSE_SUPABASE_URL = '${PULSE_SUPABASE_URL}';
window.PULSE_SUPABASE_ANON_KEY = '${PULSE_SUPABASE_ANON_KEY}';
window.PULSE_STORAGE_BACKEND = '${PULSE_STORAGE_BACKEND}';
window.PULSE_ENV = '${PULSE_ENV}';
window.PULSE_BUILD_VERSION = '${PULSE_BUILD_VERSION}';
EOF

echo "[build] Generated js/pulse-config.local.js"

# ── Inject build version into HTML cache-buster query strings ──
if command -v sed &>/dev/null; then
  echo "[build] Updating cache-buster version in HTML files..."
  for f in pages/*.html index.html; do
    [ -f "$f" ] || continue
    sed -i.bak \
      -e "s|/js/shared\.js?v=[^\"']*|/js/shared.js?v=${PULSE_BUILD_VERSION}|g" \
      -e "s|/js/supabase-client\.js?v=[^\"']*|/js/supabase-client.js?v=${PULSE_BUILD_VERSION}|g" \
      -e "s|/js/auth\.js?v=[^\"']*|/js/auth.js?v=${PULSE_BUILD_VERSION}|g" \
      "$f"
    rm -f "${f}.bak"
  done
  echo "[build] Cache-buster updated to $PULSE_BUILD_VERSION in all HTML files"
fi

echo "[build] Done — publish directory: ."
